#Requires -Version 5.1
<#
.SYNOPSIS
  Build the unsigned Kube Workspaces agent Windows MSI from a staged tag archive.

.DESCRIPTION
  Harvests kw-agent.exe (required) and the enrollment scripts (optional) from
  a directory holding the extracted tag-archive contents, generates the WiX
  payload fragment, and runs `wix build` (WiX v4/v5) against the skeleton in
  this directory.

  The MSI is UNSIGNED and FILES-ONLY: install hygiene (Add/Remove entry,
  upgrade/uninstall), not enrollment. SmartScreen warns the same as the zip.

.PARAMETER Version
  Release tag, e.g. v0.1.0. Sanitized to an MSI ProductVersion (X.Y.Z);
  dev/dirty strings fall back to 0.0.0 so main-branch validation builds work.

.PARAMETER Arch
  amd64 or arm64 (mapped to wix -arch x64 / arm64).

.PARAMETER StagingDir
  Directory with the extracted archive files (kw-agent.exe, ...).

.PARAMETER OutFile
  Output .msi path.

.PARAMETER WxsDir
  Directory holding workspace-agent.wxs (defaults to this script's dir).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File packaging/windows/build-msi.ps1 `
    -Version v0.1.0 -Arch amd64 `
    -StagingDir C:\staging\workspace-agent-windows-amd64 `
    -OutFile dist\workspace-agent-v0.1.0-windows-amd64.msi
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)][string]$Version,
  [Parameter(Mandatory = $true)][ValidateSet("amd64", "arm64")][string]$Arch,
  [Parameter(Mandatory = $true)][string]$StagingDir,
  [Parameter(Mandatory = $true)][string]$OutFile,
  [string]$WxsDir = $PSScriptRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-MsiProductVersion([string]$tag) {
  # Windows Installer compares three fields, with limits 255.255.65535.
  # Never silently truncate an unrepresentable release version.
  if ($tag -notmatch '^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$') {
    return "0.0.0"
  }
  $nums = @([long]$Matches[1], [long]$Matches[2], [long]$Matches[3])
  if ($nums[0] -gt 255 -or $nums[1] -gt 255 -or $nums[2] -gt 65535) {
    throw "Release version '$tag' exceeds MSI limits (255.255.65535)."
  }
  return ($nums -join '.')
}

function Get-SafeId([string]$name) {
  # WiX identifiers: letters, digits, underscore; must not start with a digit.
  $id = $name -replace '[^A-Za-z0-9_]', '_'
  if ($id -match '^[0-9]') { $id = '_' + $id }
  return $id
}

# $PSScriptRoot comes back empty when the script is invoked via a relative
# -File path from a UNC working directory; fall back to the invocation path.
if ([string]::IsNullOrEmpty($WxsDir)) {
  $WxsDir = Split-Path -Parent $MyInvocation.MyCommand.Path
}
if ([string]::IsNullOrEmpty($WxsDir)) {
  Write-Error "Cannot resolve the packaging directory. Re-run with an absolute script path."
  exit 1
}

if (-not (Test-Path $StagingDir -PathType Container)) {
  Write-Error "StagingDir not found: $StagingDir"
  exit 1
}
$staging = (Resolve-Path $StagingDir).Path
$OutFile = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutFile)

$exe = Join-Path $staging "kw-agent.exe"
if (-not (Test-Path $exe -PathType Leaf)) {
  Write-Error "Required agent binary missing: $exe"
  exit 1
}

# Payload contract: the agent exe plus the enrollment scripts it ships with.
# README.md/LICENSE stay out of the MSI (the archive and the image recipe own
# them); anything else staged is a contract change, so warn before including.
$payload = @("kw-agent.exe")
foreach ($opt in @("install.ps1", "uninstall.ps1")) {
  if (Test-Path (Join-Path $staging $opt) -PathType Leaf) { $payload += $opt }
}
$known = @("kw-agent.exe", "install.ps1", "uninstall.ps1", "README.md", "LICENSE")
foreach ($item in Get-ChildItem $staging -File) {
  if ($known -notcontains $item.Name) {
    Write-Warning "Staging holds unexpected file '$($item.Name)'; including it in the MSI."
    $payload += $item.Name
  }
}

$productVersion = Get-MsiProductVersion $Version
Write-Host "ProductVersion: $productVersion (from $Version)"

$wixArch = @{ amd64 = "x64"; arm64 = "arm64" }[$Arch]
$skeleton = Join-Path $WxsDir "workspace-agent.wxs"
if (-not (Test-Path $skeleton -PathType Leaf)) {
  Write-Error "WiX skeleton missing: $skeleton"
  exit 1
}

# Generated fragment: one 64-bit component per payload file. The agent's File
# Id is the fixed contract AgentExe (verify-msi.ps1 checks it).
$fragment = Join-Path ([System.IO.Path]::GetTempPath()) ("kw-files-" + [System.Guid]::NewGuid().ToString("N") + ".wxs")
$lines = @(
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by build-msi.ps1; do not edit. Lists the staged payload. -->',
  '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">',
  '  <Fragment>',
  '    <ComponentGroup Id="PayloadFiles">'
)
foreach ($file in $payload) {
  $fileId = "AgentExe"
  if ($file -ne "kw-agent.exe") { $fileId = "File_" + (Get-SafeId $file) }
  $compId = "Comp_" + (Get-SafeId $file)
  $src = [System.Security.SecurityElement]::Escape((Join-Path $staging $file))
  $lines += "      <Component Id=`"$compId`" Directory=`"INSTALLDIR`" Bitness=`"always64`" Guid=`"*`">"
  $lines += "        <File Id=`"$fileId`" Source=`"$src`" KeyPath=`"yes`" />"
  $lines += '      </Component>'
}
$lines += @(
  '    </ComponentGroup>',
  '  </Fragment>',
  '</Wix>'
)
[System.IO.File]::WriteAllLines($fragment, ([string[]]$lines), [System.Text.Encoding]::UTF8)
Write-Host "Payload: $($payload -join ', ')"

try {
  $wix = Get-Command wix -ErrorAction SilentlyContinue
  if (-not $wix) {
    Write-Host "WiX CLI not found; installing via dotnet tool..."
    & dotnet tool install --global wix --version 5.0.2 | Write-Host
    if ($LASTEXITCODE -ne 0) { throw "WiX tool installation failed ($LASTEXITCODE)." }
    $wix = Get-Command wix -ErrorAction SilentlyContinue
  }
  if (-not $wix) {
    Write-Error "WiX CLI (wix) still unavailable after install; need dotnet SDK + WiX v4/v5."
    exit 1
  }
  & wix --version | Write-Host
  # Pin the standard Windows Installer dialogs alongside the compiler. The
  # extension cache is per-user; repeated builds reuse the downloaded package.
  & wix extension add --global WixToolset.UI.wixext/5.0.2 | Write-Host
  if ($LASTEXITCODE -ne 0) { throw "WiX UI extension installation failed ($LASTEXITCODE)." }

  $outDir = Split-Path $OutFile -Parent
  if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

  & wix build $skeleton $fragment `
    -ext WixToolset.UI.wixext/5.0.2 `
    -arch $wixArch `
    -d ProductVersion=$productVersion `
    -o $OutFile
  if ($LASTEXITCODE -ne 0) {
    Write-Error "wix build failed (exit $LASTEXITCODE)."
    exit 1
  }

  # Verify the authored database read-only; never mutate it after validation.
  & (Join-Path $WxsDir "verify-msi.ps1") -Path $OutFile -Arch $Arch -Version $productVersion -StagingDir $staging
  Write-Host "Built $OutFile"
}
finally {
  Remove-Item $fragment -ErrorAction SilentlyContinue
}
